### PR TITLE
Exclude `group =>` from being treated as a group resource

### LINKED ISSUE #10: Differentiation between type and attribute not working for "group"
The match:

syn match puppetType "\<group\>"

works for any usage of the type group as in:

group { 'groupname': }

however, since it matches from above, when you're doing a standard attribute "group", the highlighting is off:

file { '/etc/foo':
  ensure => 'file',
  owner  => 'foo',
  group   => 'bar',
}

the "group" attribute carries the syntax highlighting intended for the type.  As a result, stanza highlighting is off for resources that use the group attribute.

A match would be needed that checks whether the keyword "group" is being used as a resource type or as an attribute.

### PR DESCRIPTION
**Pull request by rnelson0**
Fixes #10 

I'm a novice at vim-script, I don't know how to adequately test this for regression. I'll attach a screenshot of some sample files that look okay now.

### CODE REVIEW

**Comment by rski** [comment]
Ah is a nice solution, @rnelson0 care to do this for all the other ambiguous values like `file`?

**Comment by rnelson0** [comment]
An alternative would be to use `"group\( \+{\)\@="` which would only match `group` followed by some spaces and a left curly brace. That would prevent `group` from turning green while typing until you enter the `=>` at which point it returns to a blue. I think that might be better?

Definitely want to get review on this and trial it for a bit before hitting other values.

**Comment by rnelson0** [comment]
image

**Comment by rnelson0** [comment]
You can see how currently the `group` is treated as a resource type until the FARROW is completed. However the other group params are treated as params regardless of spacing.

**Comment by rski** [comment]
yes, the second sounds saner. I wish I could test it and provide feedback but i won't have internet at home for a while yet.

**Comment by rnelson0** [comment]
PR updated, anyone can try this by pointing to the branch `rnelson0-patch-1`, for example:
```
  vcsrepo {'/usr/share/vim/puppet':
    ensure   => latest,
    provider => git,
    source   => 'https://github.com/voxpupuli/vim-puppet.git',
    revision => 'rnelson0-patch-1',
  } 
```

image

**Comment by pegasd** [comment]
Anybody finds it weird that we're inventing hacks for some parts of the resource declaration NOT to be treated as another resource declaration?
I like rodjek's module's logic better: https://github.com/rodjek/vim-puppet/blob/master/syntax/puppet.vim
Parameters are treated as such only after we find a trailing '=>' afterwards. Otherwise, everything inside a resource declaration is treated as plain text.

**Comment by rnelson0** [comment]
Can't say I'm surprised, as I definitely have no idea what I'm doing in Vimscript! I'll close this out, there's got to be a better way to get @thallgren's updates merged against the original format.

**Pull request closed without merging**
