### PR TITLE
Refactor syntax to fix highlighting issues and add more syntax support

### PR DESCRIPTION
**Pull request by yvigara**
This is a pretty big refactoring and almost a complete rewrite of the syntax script.
It fixes a lot of syntax highlighting issues I had and globally add a better syntax support.
I've been working with it for a couple of months on my puppet 3 code base and haven't found any major issue.
I haven't tested it with puppet 4 code but I have backported the recent changes including the application orchestration.
The best way to test it is to open your puppet code and see the difference.

### CODE REVIEW

**Comment by rski** [comment]
Hi @yvigara , can you expand a bit more on the issues that you had? Does it also solve any of the existing issues?

**Comment by yvigara** [comment]
It doesn't solve any of the current issues, but it should be fairly easy now to resolve the issue #2 

Here is some of the issues I had:
- Class/define parameters highlighting was broken when using a function (for example $value = hiera('hiera_value', 'empty') )
- parameters starting with a 'i' were not highlighted correctly
- functions were not highlighted
- some keywords were not detected and highlighted correctly

The patch add the following highlighting:
- Functions and functions within functions
- Relationships and ordering (->, ~>,... symbols)
- Resources reference (Class['myclass'], File['/etc/test'] )
- Resource collector (User <| title == 'luke' |> )

**Comment by yvigara** [comment]
Current syntax highlighting:
puppet-syntax-before

Patched syntax highlighting:
puppet-syntax-after

**Comment by jyaworski** [comment]
Please rebase.

**Comment by bastelfreak** [comment]
Hi. Thanks for raising this PR, but I'm going to close it due to inactivity. Please reopen it if you're still interested in getting this merged.

**Pull request closed without merging**
